### PR TITLE
fix(reproducer): coerce sub-panel sequence args to numpy on embed replay (fixes streamplot single-embed)

### PR DESCRIPTION
**Pull request by ywatanabe1989**
## Problem (surfaced by the all-plotters nested round-trip matrix, #216)

Embedding a saved `streamplot` recipe as a single managed sub-panel via `ax.embed` failed to reproduce: `UserWarning: Failed to replay streamplot: 'CommentedSeq' object has no attribute 'shape'` → the embedded sub-panel never redrew → validation MSE ~1639. (xfail'd in #216.)

## Root cause

The data-file loader (`_serializer/_load._resolve_data_references`) only descends into top-level `axes[...].calls`, **not** into `subpanels`. So a sub-panel's coordinate arrays round-trip as ruamel `CommentedSeq` lists (not numpy), and `Axes.streamplot` calls `.shape` on them. Standalone / `fr.compose` / embed-of-composed all worked (their data goes to CSV files the loader resolves to ndarrays) — only the direct single-embed path didn't coerce.

## Fix

`coerce_sequence_arg()` in `_reproducer/_reconstruct.py` promotes plain list/tuple args to `np.asarray` (leaving object-dtype/heterogeneous/empty sequences as-is); `_replay_call` gains a `coerce_sequences` flag used by the sub-panel replay paths (`_replay_insets.replay_subpanels` + `_axes_embed._draw_and_record_source`). General (not streamplot-specific); main replay path unchanged.

## Verification
- The `streamplot` single-embed xfail is **removed** and now passes as a normal test.
- No regressions: `_reproducer` 70 passed; `test_embed_reproduction.py` + `test_inset_reproduction.py` 9 passed; composition + compose-of-composed streamplot pass.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by ywatanabe1989** [comment]
Superseded by the consolidated PR #224 (which includes this streamplot embed fix). Closing.
